-- MySQL Script generated by MySQL Workbench
-- 10/30/16 13:54:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema u910751258_fasty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u910751258_fasty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b5_19129423_Fasty` DEFAULT CHARACTER SET utf8 ;
USE `b5_19129423_Fasty` ;

-- -----------------------------------------------------
-- Table `b5_19129423_Fasty`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b5_19129423_Fasty`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `codigoSeguridad` VARCHAR(4) NOT NULL,
  `administrador` TINYINT(1) NOT NULL DEFAULT 0,
  `password` VARCHAR(45) NOT NULL,
  `correoConfirmado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b5_19129423_Fasty`.`Establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b5_19129423_Fasty`.`Establecimiento` (
  `idEstablecimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(11) NOT NULL,
  `descripcion` VARCHAR(190) NOT NULL,
  `longitud` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `linkImagen` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstablecimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `b5_19129423_Fasty`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b5_19129423_Fasty`.`Calificacion` (
  `estrellas` INT NULL,
  `comentario` VARCHAR(140) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Establecimiento_idEstablecimiento` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Establecimiento_idEstablecimiento`),
  INDEX `fk_Calificacion_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Calificacion_Establecimiento1_idx` (`Establecimiento_idEstablecimiento` ASC),
  CONSTRAINT `fk_Calificacion_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `b5_19129423_Fasty`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Establecimiento1`
    FOREIGN KEY (`Establecimiento_idEstablecimiento`)
    REFERENCES `b5_19129423_Fasty`.`Establecimiento` (`idEstablecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
